version: "3.9"

services:
  discord-channel-cloner:
    build: .
    container_name: discord-channel-cloner
    environment:
      TOKEN: ${TOKEN}
    volumes:
      - /app-config:/config
    restart: unless-started
