version: "3.9"

services:
  discord-channel-cloner:
    image: ghcr.io/exilvm/discordchannelcloner:master
    container_name: discord-channel-cloner
    environment:
      TOKEN: ${TOKEN}
    volumes:
      - ${CONFIG_DIRECTORY}:/config
    restart: unless-stopped
